### PR TITLE
Create coin_change_one_liner.py

### PR DESCRIPTION
**Pull request by Blacksnblack**
Added a new file with the one-liner ☺

### CODE REVIEW

**Comment by Blacksnblack** [comment]
- Btw, this is Terry Black from class

**Review by LicenseToSoftware — APPROVED** [review]
It took me a minute to understand what was going on. I've never used the walrus operator before. That's very cool.

**Comment by Blacksnblack** [comment]
Right?! Tbh, I just learned about it recently myself and now I wanna use it everywhere 😂😂

**Comment by LicenseToSoftware** [comment]
I just wish had a similar operator for life XD.

**Pull request merged**
